module.exports = {
  MAIN_SERVER: 'https://studio.amadeus-video-solutions.com',
  VIMEO_API_KEY: 'SOME_VIMEO_API_KEY',
  DEFAULT_VIDEO_ID: '5adda788b9ac5a0001089ada',
  API_KEY: 'bcfe74fb-3609-4caa-bac2-fcd11a5ceb6d',
  GOOGLE_MAP_API_KEY : 'SOME_GOOGLE_MAP_API_KEY',
  GOOGLE_ANALYTICS_TRACKING_CODE : 'SOME_GOOGLE_ANALYTICS_TRACKING_CODE',
  IP_STACK_API_KEY : 'SOME_IP_STACK_API_KEY'
};
