export default {
  MAIN_SERVER : 'MAIN_SERVER',
  VIMEO_API_KEY : 'VIMEO_API_KEY',
  DEFAULT_VIDEO_ID : 'DEFAULT_VIDEO_ID',
  API_KEY : 'API_KEY',
  GOOGLE_MAP_API_KEY : 'GOOGLE_MAP_API_KEY',
  GOOGLE_ANALYTICS_TRACKING_CODE : 'GOOGLE_ANALYTICS_TRACKING_CODE',
  IP_STACK_API_KEY : 'IP_STACK_API_KEY'
};